title: Antti-Juhana Mäki, PhD
# logo: /pics/photo_ajmaki.png
logo: "https://raw.githubusercontent.com/AnaHill/AnaHill.github.io/main/pics/headshot_circle_ajm.png"
show_downloads: true
theme: jekyll-theme-minimal
